units:
  cxx: cx+1
  cyy: cy+5
  mcx: 1.25 cx
  mcy: 2.25 cy 
points:
   key:
      padding: 1.15 cy
      footprints:
          choc_hotswap:
            type: choc
            nets:
              from: =column_net
              to: GND
            params:
                keycaps: true
                reverse: true
                hotswap: true
          choc:
            type: choc
            anchor:
              rotate: 180
            nets:
              from: =column_net
              to: GND
            params:
                keycaps: true
                reverse: true
   zones:
    board:
      rotate: 30 # check the outlines when not 0
      rows:
        bottom:
        home:
        top:
      columns:          
          pinkie:
            spread: cxx
            rotate: 0
            rows:
              top:
                bind: [0, 0] 
                column_net: P0
                rotate: -10
              home:
                column_net: PX
                bind: [0, 0] 
              bottom:
                shift: [3, 0]
                bind: [0, 0] 
                column_net: PX
          ring:
            stagger: 12
            rotate: -105+90
            origin: [-cy*2.2, -cx*1.8]
            spread: cxx
            rows: 
              bottom:
                column_net: PX
              home: 
                column_net: PX
              top: 
                column_net: P1
          middle: 
            stagger: 5
            spread: cxx
            rotate: -9
            origin: [-cy*3.5, -cx*0.9]
            rows: 
              bottom:
                column_net: PX
              home: 
                column_net: PX
              top:
                column_net: P2
          index: 
            stagger: -6
            rotate: -5
            spread: cxx
            rows: 
              bottom:
                column_net: PX
              home: 
                column_net: PX
              top: 
                column_net: P3
          far: 
            stagger: -(cy/1.5)
            spread: cxx
            origin: [-cy, -cx]
            rows: 
              bottom:
                #bind: [0, 2.5cx, 0, 0]
                column_net: PX
              home: 
                #bind: [0, 2.5cx, 0, 0]
                column_net: PX 
              top: 
                #bind: [0, 2.5cx, 0, 0]
                column_net: P5
    thumbfan:
      anchor:
        ref: board_pinkie_bottom
        shift: [18*2.65, -18*3.5]
        orient: 0
      columns:
        near:
          rotate: -44
          rows:
            thumb:
              column_net: P8
        home:
          rotate: -5
          origin: [-15, -15]          
          rows:
            thumb:
             column_net: P7
        far:
          rotate: -10
          origin: [-15, -15]
          rows:
            thumb:
             column_net: P6
            plop:
             shift: [0.75 cx, -2.25 cx]
             column_net: P5
      rows:
        #thumb:
         #column_net: P21
outlines:
  exports:
    raw: 
      main:
        type: keys
        side: left
        size: [cx, cx]
        bevel: 2
        corner: 2
    filler:
      - type: polygon
        points:
        - ref: board_pinkie_top
          shift: [-0.75 cx, 0.5cx]
        - ref: board_ring_top
          shift: [-10, 0.6 cx]          
        - ref: board_middle_top
          shift: [-5, 0.75 cx]
        - ref: board_index_top
          shift: [cx, .6 cx]
        - ref: board_far_top
          shift: [2 cx, 2]
        - ref: thumbfan_far_thumb
          shift: [1.25 cx, 10]
        - ref: thumbfan_far_plop
          shift: [0.65cx, -0.61cx]
        - ref: board_pinkie_bottom
          shift: [-cx, -50]
    mc:
      main:
        type: rectangle
        anchor:
          ref:
            - board_far_home
          shift: [mcx/2, -1mcy]
        size: [mcx, 3cy] 
    cutout:
      - type: outline
        name: raw
        #fillet: 5
      - type: outline
        name: filler
        fillet: 5
        operation: stack
    keycap_outlines:
      - type: keys
        side: left
        size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
        bound: false               
    demo:
        - type: outline
          name: keycap_outlines
        - type: outline
          name: filler
          operation: stack
pcbs:
  mine:
    outlines:
      main:
        outline: cutout
    footprints:
      promicro:
        type: promicro_pretty
        anchor:
          ref: board_far_home
          shift: [1.3 cx, -0.5 cx]
          rotate: -90
        params:
          orientation: down
      via3:
        type: via
        anchor: 
          ref: board_pinkie_bottom
          shift: [-2,-10]
        nets: 
          net: RAW 
      via4:
        type: via
        anchor: 
          ref: board_pinkie_bottom
          shift: [-4,-10]
        nets: 
          net: pos 
      via5:
        type: via
        anchor: 
          ref: board_pinkie_bottom
          shift: [8,-10]
        nets: 
          net: GND 
      via6:
        type: via
        anchor: 
          ref: board_pinkie_bottom
          shift: [6,-10]
        nets: 
          net: RST 
      pcm12:
        type: pcm12
        anchor:
          ref: board_far_home
          shift: [2 cx, 0]
          rotate: 90
        nets:
          from: pos  
          to: RAW
        params:
          reverse: true 
      b3u1000p:
        type: b3u1000p
        nets:
          r1: RST  
          r2: GND
        anchor:
          ref: board_far_home
          shift: [2 cx, -9]
          rotate: 90
        params:
          reverse: true 
      bat:
        type: bat
        nets: 
          neg: GND
        anchor:
          ref: board_far_bottom
          shift: [1 cx, -10]
          rotate: 0
