units:
  cxx: cx+1
  cyy: cy+5
  mcx: 1.25cx
  mcy: 2.25cy 
points:
   key:
      padding: cy*1.15
      footprints:
          choc_hotswap:
            type: choc
            nets:
              from: =column_net
              to: GND
            params:
                keycaps: true
                reverse: true
                hotswap: true
          choc:
            type: choc
            anchor:
              rotate: 180
            nets:
              from: =column_net
              to: GND
            params:
                keycaps: true
                reverse: true
   zones:
    board:
      rotate: 30 # check the outlines when not 0
      rows:
        bottom:
        home:
        top:
      columns:          
          pinkie:
            spread: cxx
            rotate: 0
            rows:
              top:
                bind: [0, 0] 
                column_net: P21
                rotate: -10
              home:
                column_net: P20
                bind: [0, 0] 
              bottom:
                shift: [3, 0]
                bind: [0, 0] 
                column_net: P21
          ring:
            stagger: 12
            rotate: -105+90
            origin: [-cy*2.2, -cx*1.8]
            spread: cxx
            rows: 
              bottom:
                #bind: [0, 1, 1.5cy, 1] # defines the extent of the border for the cutout [num_t, num_r, num_b, num_l]
                column_net: P19
              home: 
                column_net: P18
              top: 
                column_net: P15
          middle: 
            stagger: 5
            spread: cxx
            rotate: -9
            origin: [-cy*3.5, -cx*0.9]
            rows: 
              bottom:
                #bind: [0, 1, 1.5cy, 1] # defines the extent of the border for the cutout [num_t, num_r, num_b, num_l]
                column_net: P14
              home: 
                column_net: P16
              top:
                column_net: P10
          index: 
            stagger: -6
            rotate: -5
            spread: cxx
            rows: 
              bottom:
                #bind: [0, 1, 1.5cy, 1] # defines the extent of the border for the cutout [num_t, num_r, num_b, num_l]
                column_net: P4
              home: 
                column_net: P5
              top: 
                column_net: P6
          far: 
            stagger: -(cy/1.5)
            spread: cxx
            origin: [-cy, -cx]
            rows: 
              bottom:
                #bind: [0, 2.5cx, 0, 0]
                column_net: P9
              home: 
                #bind: [0, 2.5cx, 0, 0]
                column_net: P7 
              top: 
                #bind: [0, 2.5cx, 0, 0]
                column_net: P8
    thumbfan:
      anchor:
        ref: board_pinkie_bottom
        shift: [18*2.65, -18*3.5]
        orient: 0
      columns:
        near:
          rotate: -44
        home:
          rotate: -5
          origin: [-15, -15]          
        far:
          rotate: -10
          origin: [-15, -15]
          rows:
           plop:
            shift: [-1, -cx*2 -5]
            column_net: P21
      rows:
        thumb:
         column_net: P21
outlines:
  exports:
    raw: 
      main:
        type: keys
        side: left
        size: [1.5cx , 1.5cx]
    filler:
      - type: polygon
        points:
        - ref: board_pinkie_top
          shift: [-1.1 cx, cx]
        - ref: board_ring_top
          shift: [-10, cx]          
        - ref: board_middle_top
          shift: [-5, 1.3 cx]
        - ref: board_middle_top
          shift: [17, 1.1 cx]
        - ref: board_far_top
          shift: [2 cx, 2]
        - ref: thumbfan_far_thumb
          shift: [0.9 cx, 10]
        - ref: thumbfan_far_plop
          shift: [cx, -1cx]
        - ref: board_pinkie_bottom
          shift: [-cx, -50]
    mc:
      main:
        type: rectangle
        anchor:
          ref:
            - board_far_home
          shift: [mcx/2, -1mcy]
        size: [mcx, 3cy] 
    cutout:
      - type: outline
        name: raw
        fillet: 5
      - type: outline
        name: mc
        fillet: 5
      - type: outline
        name: filler
        fillet: 5
        #operation: stack
    keycap_outlines:
      - type: keys
        side: left
        size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
        bound: false               
pcbs:
  mine:
    outlines:
      main:
        outline: cutout
    footprints:
      promicro:
        type: promicro
        anchor:
          ref: board_far_home
          shift: [1.2cx, -0.5cx]
          rotate: -90
        params:
          orientation: down
      pcm12:
        type: pcm12
        anchor:
          ref: board_far_home
          shift: [-75, -22]
          rotate: 0
        nets:
          from: pos  
          to: RAW
        params:
          reverse: true 
      via3:
        type: via
        anchor: 
          ref: board_pinkie_bottom
          shift: [-2,-10]
        nets: 
          net: RAW 
      via4:
        type: via
        anchor: 
          ref: board_pinkie_bottom
          shift: [-4,-10]
        nets: 
          net: pos 
      via5:
        type: via
        anchor: 
          ref: board_pinkie_bottom
          shift: [8,-10]
        nets: 
          net: GND 
      via6:
        type: via
        anchor: 
          ref: board_pinkie_bottom
          shift: [6,-10]
        nets: 
          net: RST 
      b3u1000p:
        type: b3u1000p
        nets:
          r1: RST  
          r2: GND
        anchor:
          ref: board_pinkie_bottom
          shift: [7, -15]
          rotate: 0
        params:
          reverse: true 
      bat:
        type: bat
        nets: 
          neg: GND
        anchor:
          ref: board_far_bottom
          shift: [-42 , -0]
          rotate: 0
#units:
#  cx: 18 # defaults: choc x 18mm
#  cy: 17 #           choc y 17mm
#points:
#  key:
#    padding: cy
#    footprints:
#      choc_hotswap:
#        type: choc
#        nets:
#          from: =column_net
#          to: GND
#      params:
#        keycaps: true
#        reverse: true
#        hotswap: true
#      choc:
#        type: choc
#        anchor:
#          rotate: 180
#        nets:
#          from: =column_net
#          to: GND
#        params:
#          keycaps: true
#          reverse: true
#  zones:
#    matrix:
#      anchor:
#        rotate: 5
#      columns:
#        pinky:
#        ring:
#          rotate: -5
#          origin: [-12, -19]
#          stagger: 12
#        middle:
#          stagger: 5
#        index:
#          stagger: -6
#        inner:
#          stagger: -2
#      rows:
#        bottom:
#        home:
#        top:
#    thumbfan:
#      anchor:
#        ref: matrix_inner_bottom
#        shift: [-7, -19]
#      columns:
#        near:
#        home:
#          spread: 21.25
#          rotate: -28
#          origin: [-11.75, -9]
#        far:
#          spread: 21.25
#          rotate: -28
#          origin: [-9.5, -9]
#      rows:
#        thumb:
#  rotate: -20


