units:
  cxx: cx+0.5
  cyy: cy+5
points:
   key:
      padding: cy*1.15
      footprints:
          choc_hotswap:
            type: choc
            nets:
              from: =column_net
              to: GND
            params:
                keycaps: true
                reverse: true
                hotswap: true
          choc:
            type: choc
            anchor:
              rotate: 180
            nets:
              from: =column_net
              to: GND
            params:
                keycaps: true
                reverse: true
   zones:
    board:
      rotate: 0 #30 # check the outlines when not 0
      rows:
        bottom:
        home:
        top:
      columns:          
          pinkie:
            spread: cxx
            rotate: 0
            rows:
              top:
                column_net: P21
                bind: [0.5, 3, 3, 1]
              bottom:
                bind: [0, 0, 0, 1] # defines the extent of the border for the cutout [num_t, num_r, num_b, num_l]
                column_net: P21
              home:
                bind: [0.5, 3, 3, 1]
                column_net: P20
          ring:
            stagger: 12
            rotate: -105+90
            origin: [-cy*2.2, -cx*1.8]
            spread: cxx
            rows: 
              bottom:
                bind: [0, 0, 2, 3]
                column_net: P19
              home: 
                bind: [3,0,3,1]
                column_net: P18
              top: 
                bind: [0.5,3,0,1]
                column_net: P15
          middle: 
            stagger: 5
            spread: cxx
            rotate: -9
            origin: [-cy*3.5, -cx*0.9]
            rows: 
              bottom:
                bind: [0, 3, 20, 3]
                column_net: P14
              home: 
                bind: [3,0,3,0]
                column_net: P16
              top:
                column_net: P10
                bind: [0.5,1,0,1]
          index: 
            stagger: -6
            rotate: -5
            spread: cxx
            rows: 
              bottom:
                bind: [0, 3, 0, 0]
                column_net: P4
              home: 
                bind: [3,0,3,0]
                column_net: P5
              top: 
                bind: [0.5,1,3,3]
                column_net: P6
          far: 
            stagger: -(cy/2)
            spread: cxx
            origin: [-cy, -cx]
            rows: 
              bottom:
                bind: [3,1, 0, 73]
                column_net: P9
              home: 
                bind: [3,1,3,0]
                column_net: P7 
              top: 
                bind: [0.5,1,3,3]
                column_net: P8
    thumb_fan:
      anchor:
        ref: board_index_bottom
        shift: [-7, -19]
      columns:
        near:
        home:
        far:
      rows:
        thumb:
         column_net: P21

outlines:
  exports:
    raw: 
      - type: keys
        side: left
        size: [1cx , 1cx]
    cutout:
      - type: outline
        name: raw
        fillet: 3
    keycap_outlines:
      - type: keys
        side: left
        size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
        bound: false               
pcbs:
  mine:
    outlines:
      main:
        outline: cutout
    footprints:
      promicro:
        type: promicro
        anchor:
          ref: board_far_home
          shift: [-25, -17]
          rotate: 0
        params:
          orientation: down
      pcm12:
        type: pcm12
        anchor:
          ref: board_far_home
          shift: [-75, -22]
          rotate: 0
        nets:
          from: pos  
          to: RAW
        params:
          reverse: true 
      via3:
        type: via
        anchor: 
          ref: board_pinkie_bottom
          shift: [-2,-10]
        nets: 
          net: RAW 
      via4:
        type: via
        anchor: 
          ref: board_pinkie_bottom
          shift: [-4,-10]
        nets: 
          net: pos 
      via5:
        type: via
        anchor: 
          ref: board_pinkie_bottom
          shift: [8,-10]
        nets: 
          net: GND 
      via6:
        type: via
        anchor: 
          ref: board_pinkie_bottom
          shift: [6,-10]
        nets: 
          net: RST 
      b3u1000p:
        type: b3u1000p
        nets:
          r1: RST  
          r2: GND
        anchor:
          ref: board_pinkie_bottom
          shift: [7, -15]
          rotate: 0
        params:
          reverse: true 
      bat:
        type: bat
        nets: 
          neg: GND
        anchor:
          ref: board_far_bottom
          shift: [-42 , -0]
          rotate: 0
#units:
#  cx: 18 # defaults: choc x 18mm
#  cy: 17 #           choc y 17mm
#points:
#  key:
#    padding: cy
#    footprints:
#      choc_hotswap:
#        type: choc
#        nets:
#          from: =column_net
#          to: GND
#      params:
#        keycaps: true
#        reverse: true
#        hotswap: true
#      choc:
#        type: choc
#        anchor:
#          rotate: 180
#        nets:
#          from: =column_net
#          to: GND
#        params:
#          keycaps: true
#          reverse: true
#  zones:
#    matrix:
#      anchor:
#        rotate: 5
#      columns:
#        pinky:
#        ring:
#          rotate: -5
#          origin: [-12, -19]
#          stagger: 12
#        middle:
#          stagger: 5
#        index:
#          stagger: -6
#        inner:
#          stagger: -2
#      rows:
#        bottom:
#        home:
#        top:
#    thumbfan:
#      anchor:
#        ref: matrix_inner_bottom
#        shift: [-7, -19]
#      columns:
#        near:
#        home:
#          spread: 21.25
#          rotate: -28
#          origin: [-11.75, -9]
#        far:
#          spread: 21.25
#          rotate: -28
#          origin: [-9.5, -9]
#      rows:
#        thumb:
#  rotate: -20


